In [2]:
import numpy as np

In [3]:
# Creation of a simple array
arr_1D = np.array ([1, 2, 3, 4, 5])
print (arr_1D.shape)
print (arr_1D.size)
print (arr_1D)

(5,)
5
[1 2 3 4 5]


In [13]:
# Creation of a 2D array
arr_2D = np.array ([[1, 1, 1],[1, 2, 1], [1,3 ,1]])
print (arr_2D.shape)
print (arr_2D.size)
print (arr_2D)

# Creation of a 3D array
arr_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10],[12, 13] ]])
print(arr_3D.shape)
print(arr_3D.size)
print(arr_3D)  

arr_3d_reshape = arr_3D.reshape(2, 3, 2)
print(arr_3d_reshape.shape)
print(arr_3d_reshape.size)  
print(arr_3d_reshape)
# Creation of an array with zeros   
arr_zeros = np.zeros((2, 3))
print(arr_zeros.shape)

(3, 3)
9
[[1 1 1]
 [1 2 1]
 [1 3 1]]
(3, 2, 2)
12
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [12 13]]]
(2, 3, 2)
12
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [12 13]]]
(2, 3)


In [20]:
# Accessing the array index. Note the diff between a list access
x = arr_2D[0:3,0:1]
print (type(x))
print (x)

# Get a row completely
r = arr_2D [1, :]
print (type(r))
print (r)

# Get a column completely
c = arr_2D [:, 1]
print (type(c))
print (c)


<class 'numpy.ndarray'>
[[1]
 [1]
 [1]]
<class 'numpy.ndarray'>
[1 2 1]
<class 'numpy.ndarray'>
[1 2 3]


In [21]:
# Creation of a 2D array
arr_2D = np.array ([[1, 1, 1],[1, 2, 1], [1,3 ,1]])
print (arr_2D.shape)
print (arr_2D.size)
print (arr_2D)

# Get a sub-array
sub_arr = arr_2D[0:2, 1:3]  
print(type(sub_arr))
print(sub_arr)  
# Get a sub-array with step
sub_arr_step = arr_2D[0:3:2, 0:3:2] 
print(type(sub_arr_step))
print(sub_arr_step) 
# Get a sub-array with negative step
sub_arr_neg_step = arr_2D[0:3:2, 0:3:-1]
print(type(sub_arr_neg_step))
print(sub_arr_neg_step)  # This will return an empty array since the step is negative and the range is not valid
# Get a sub-array with negative step in reverse order
sub_arr_neg_step_reverse = arr_2D[0:3:2, 2:0:-1]
print(type(sub_arr_neg_step_reverse))
print(sub_arr_neg_step_reverse)  # This will return a valid sub-array with reversed columns 
# Get a sub-array with negative step in reverse order and different row range
sub_arr_neg_step_reverse_row = arr_2D[0:2:1, 2:0:-1]
print(type(sub_arr_neg_step_reverse_row))
print(sub_arr_neg_step_reverse_row)  # This will return a valid sub-array with reversed columns and limited rows

(3, 3)
9
[[1 1 1]
 [1 2 1]
 [1 3 1]]
<class 'numpy.ndarray'>
[[1 1]
 [2 1]]
<class 'numpy.ndarray'>
[[1 1]
 [1 1]]
<class 'numpy.ndarray'>
[]
<class 'numpy.ndarray'>
[[1 1]
 [1 3]]
<class 'numpy.ndarray'>
[[1 1]
 [1 2]]


In [22]:
# Create a multi-dimension array with random values
# Its a 6 dimensional array of random numbers, with each dimension length different
arr_mD = np.random.rand (12, 10, 8, 20, 15, 40)

print (arr_mD.shape)
print (arr_mD.size)

# Observe the dimensions ...
print (arr_mD[0,0,0,0,0,:],'\n')
print (arr_mD[0,0,0,0,:,0], '\n')
print (arr_mD[2,3,1,4,4,3:15])

(12, 10, 8, 20, 15, 40)
11520000
[0.88079339 0.71406203 0.67056491 0.50699714 0.72661105 0.99054897
 0.75278715 0.89285894 0.93624045 0.18315333 0.73209162 0.2006817
 0.33995072 0.32502736 0.84736994 0.91079691 0.49683149 0.52799087
 0.24118748 0.1136703  0.29237724 0.51066062 0.45213271 0.63537073
 0.47919658 0.07842738 0.31463226 0.56163716 0.940567   0.99202701
 0.49766799 0.11392902 0.72098867 0.85642657 0.22839871 0.34703729
 0.90204372 0.58862043 0.74923926 0.74120305] 

[0.88079339 0.94787901 0.75933208 0.66982924 0.92437964 0.99045108
 0.68927248 0.99812303 0.95819608 0.01004502 0.92816486 0.9498402
 0.54720879 0.70239179 0.47862666] 

[0.12856251 0.42677325 0.46359136 0.3840591  0.51866364 0.42610357
 0.66962303 0.04200958 0.09656265 0.20461577 0.65220296 0.5944348 ]


In [ ]:
# Want to see complete array ?
print (arr_mD)

Since arrays are fixed in size, it cannot be extended on the go like list  
However there are functions provided to add elements to the array  
These functions return a new array

In [23]:
# Appending elements at the end of an existing array
arr_2D = np.array ([[1,1,1], [1,2,1], [1,3,1]])
print (arr_2D)

# Add elements along axis 0 
arr_2D_New = np.append (arr_2D, [[1,4,1]], axis=0)
print (arr_2D_New)

# Add elements along axis 1
arr_2D_New = np.append (arr_2D, [[1],[4],[1]], axis=1)
print (arr_2D_New)

[[1 1 1]
 [1 2 1]
 [1 3 1]]
[[1 1 1]
 [1 2 1]
 [1 3 1]
 [1 4 1]]
[[1 1 1 1]
 [1 2 1 4]
 [1 3 1 1]]


In [25]:
# Concatenate function can be used to merge multiple arrays into one
arr_1 = np.array ([[1,1], [1,2]])
arr_2 = np.array ([[2,1], [2,2]])

print (arr_1, '\n\n', arr_2, '\n\n')

arr_3 = np.concatenate ((arr_1, arr_2), axis=0)
print (arr_3, '\n\n')
arr_4 = np.concatenate ((arr_1, arr_2), axis=1)
print (arr_4, '\n\n')

[[1 1]
 [1 2]] 

 [[2 1]
 [2 2]] 


[[1 1]
 [1 2]
 [2 1]
 [2 2]] 


[[1 1 2 1]
 [1 2 2 2]] 




Array can be re-shaped in terms of dimension & length by reshape method  
The elements are re-arranged to the suit the required dimension, without changing the order  
That means total number of elements will have to match to the dimension and length

In [ ]:
# Make an one dimensional array in 2D array
arr = np.array ([1,2,3,4,5,6,7,8,9,10,11,12])
print (arr.shape)
print (arr)

# Reshape it into 2D
arr_2D = arr.reshape ((3,4))
print (arr_2D.shape)
print (arr_2D)

In [ ]:
# Reshape as 2D but diff length
arr_2D = arr.reshape ((4,3))
print (arr_2D.shape)
print (arr_2D)

In [ ]:
# Reshape as 3D to match the total number of elements
arr_3D = arr.reshape ((2, 2, 3))
print (arr_3D.shape)
print (arr_3D)

Arithmatic, aggregation, scalar and other mathematical operations can be done using the numpy functions  
Its done in vectorised way, hence faster

In [26]:
# Basic arithmatic operations
arr_1 = np.array ([[1, 2], [3, 4]])
arr_2 = np.array ([[5, 6], [7, 8]])

print ("Addition : \n", arr_1 + arr_2)
print ("Subtraction : \n", arr_1 - arr_2)
print ("Multiplication : \n", arr_1 * arr_2)
print ("Division : \n", arr_1 / arr_2)

Addition : 
 [[ 6  8]
 [10 12]]
Subtraction : 
 [[-4 -4]
 [-4 -4]]
Multiplication : 
 [[ 5 12]
 [21 32]]
Division : 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
# Scalar operations
print ("Scalar Addition : \n", arr_1 + 2)
print ("Scalar Multiplication : \n", arr_1 * 3.54)

Scalar Addition : 
 [[3 4]
 [5 6]]
Scalar Multiplication : 
 [[ 3.54  7.08]
 [10.62 14.16]]


In [ ]:
# Aggregation functions can be made on the array
print ("Sum of Array Elements : \n", np.sum(arr_2))
print ("Mean of Array Elements : \n", np.mean(arr_2))
print ("Min of Array Elements : \n", np.min(arr_2))
print ("Max of Array Elements : \n", np.max(arr_2))

In [ ]:
# Other Mathematical operations
print ("Square Root : \n", np.sqrt (arr_2))
print ("Sine value : \n", np.sin (arr_2))